---
title: "Focus on the Triangle"
author: "Eva Marques"
date: "2024-05-15"
output: html_document
---

Load heatwatch data 

```{r}
hw_dict <- readRDS("../input/heatwatch/heatwatch_dictionary.rds")
gridmet_dir <- "../input/gridmet/"
daymet_dir <- "../input/daymet/north_america/"
products_am <- load_temp_products_city(
  "raleigh_durham",
  hw_dict,
  gridmet_dir,
  daymet_dir,
  "am"
)
products_af <- load_temp_products_city(
  "raleigh_durham",
  hw_dict,
  gridmet_dir,
  daymet_dir,
  "af"
)
```

Load CWS data

```{r}
cws <- readRDS(paste0(
  "../input/cws/",
  "cws_rtp_cleaned_calibrated_2021-07-22_2021-07-23.rds"
))
```

Maps 

```{r}
plots <- map_cws_hw(cws,
  hw_r_am = products_am$heatwatch_r,
  hw_r_af = products_af$heatwatch_r
)
p <- ggpubr::ggarrange(plots$map_am, plots$map_af, ncol = 2)
p
ggsave(
  plot = p,
  filename = paste0("../graphs/maps_heatwatch_cws_triangle_area.png"),
  width = 16,
  height = 7,
  dpi = 200
)
```

Future analysis if previous maps are coherent: long term comparison of cws to
gridmet and daymet
