---
title: "Maps cities"
format: html
editor: visual
---

## Set up

Generate heatwatch dictionnary if not already done and set gridmet and daymet paths

```{r}
if (file.exists("../input/heatwatch/heatwatch_dictionary.rds")) {
  hw_dict <- readRDS("../input/heatwatch/heatwatch_dictionary.rds")
} else {
  hw_dict <- create_heatwatch_dictionary("../input/heatwatch/")
  hw_dict <- hw_dict[which(hw_dict$city != "milwaukee"), ]
  saveRDS(hw_dict, "../input/heatwatch/heatwatch_dictionary.rds")
}
list_cities <- unique(hw_dict$city)
gridmet_dir <- "../input/gridmet/"
daymet_dir <- "../input/daymet/north_america/"
```

TN maps

```{r}
moment_of_day <- "am"
for (c in list_cities[1]) {
  cat(c, "\n")
  p <- map_temp_products_city(
    c,
    hw_dict,
    gridmet_dir,
    daymet_dir,
    moment_of_day
  )
  print(p)
  ggsave(
    plot = p,
    filename = paste0("../graphs/maps_", c, "_", moment_of_day, ".png"),
    width = 16,
    height = 7,
    dpi = 200
  )
}
```

TX maps

```{r}
moment_of_day <- "af"
for (c in list_cities) {
  cat(c, "\n")
  p <- map_temp_products_city(
    c,
    hw_dict,
    gridmet_dir,
    daymet_dir,
    moment_of_day
  )
  print(p)
  ggsave(
    plot = p,
    filename = paste0("../graphs/maps_", c, "_", moment_of_day, "_with_traverse.png"),
    width = 16,
    height = 7,
    dpi = 200
  )
}
```
